-- Clear words table
ALTER TABLE WORDS
DROP COLUMN WORDID;

ALTER TABLE WORDS
ADD COLUMN WORDID INTEGER NOT NULL DEFAULT 9999999;
 
TRUNCATE TABLE WORDS;

ALTER TABLE WORDS
ADD CONSTRAINT WORD_ID FOREIGN KEY (WORDID) REFERENCES WORDS_LETTERS(WORDID);

-- Clear users table

ALTER TABLE USERS
DROP COLUMN ID;

TRUNCATE TABLE USERS;

ALTER TABLE USERS
ADD COLUMN ID INTEGER NOT NULL PRIMARY KEY DEFAULT 9999999;

-- Clear words letters table

ALTER TABLE WORDS_LETTERS
DROP COLUMN WORDID;

TRUNCATE TABLE WORDS_LETTERS;

ALTER TABLE WORDS_LETTERS
ADD COLUMN WORDID INTEGER  NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);

ALTER TABLE WORDS_LETTERS
ADD CONSTRAINT USER_ID_REAL FOREIGN KEY (USERID) REFERENCES USERS(ID);

